<?php
$sql =  [
    "DROP TABLE IF EXISTS `blogstags`",
    "DROP TABLE IF EXISTS `comments`",
    "DROP TABLE IF EXISTS `follows`",
    "DROP TABLE IF EXISTS `hobbies`",
    "DROP TABLE IF EXISTS `blogs`",
    "DROP TABLE IF EXISTS `users`",
    "CREATE TABLE users (`userid` int NOT NULL AUTO_INCREMENT,`username` varchar(45) CHARACTER SET utf8mb4 NOT NULL,`password` varchar(45) CHARACTER SET utf8mb4 NOT NULL,`email` varchar(45) CHARACTER SET utf8mb4 DEFAULT NULL,`first_name` varchar(45) CHARACTER SET utf8mb4 NOT NULL, `last_name` varchar(45) CHARACTER SET utf8mb4 NOT NULL,PRIMARY KEY (`userid`),CONSTRAINT `username_UNIQUE` UNIQUE  (`username`)) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci",
    "LOCK TABLES `users` WRITE",
    "INSERT INTO users VALUES (1,'batman','1234','nananana@batman,com','',''),(2,'bob','12345','bobthatsme@yahoo,com','',''),(3,'catlover','abcd','catlover@whiskers,com','',''),(4,'doglover','efds','doglover@bark,net','',''),(5,'jdoe','25478','jane@doe,com','',''),(6,'jsmith','1111','jsmith@gmail,com','',''),(7,'matty','2222','matty@csun,edu','',''),(8,'notbob','5555','stopcallingmebob@yahoo,com','',''),(9,'pacman','9999','pacman@gmail,com','',''),(10,'scooby','8888','scooby@doo,net','','')",
    "UNLOCK TABLES",
    "CREATE TABLE blogs (`blogid` int unsigned NOT NULL AUTO_INCREMENT, `subject` varchar(50) CHARACTER SET utf8mb4 DEFAULT NULL, `description` varchar(250) CHARACTER SET utf8mb4 DEFAULT NULL, `pdate` date DEFAULT NULL, `userid` int DEFAULT NULL, PRIMARY KEY (`blogid`), CONSTRAINT `blogs_ibfk_1` FOREIGN KEY (`userid`) REFERENCES users (`userid`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci",
    "CREATE INDEX `idx_blogs_pdate` ON blogs (`pdate`)",
    "CREATE INDEX `blogs_ibfk_1_idx` ON blogs (`userid`)",
    "LOCK TABLES `blogs` WRITE",
    "INSERT INTO blogs VALUES (1,'Hello World','Hey everyone, this is my first blog, Hello world and all who inhabit it!','2020-03-15',6),(2,'I love cats!',\"Cats are amazing, They're awesome, and fuzzy, and cute, Who DOESN'T love cats?\",'2020-03-17',3),(3,'Dogs are the best,',\"So I saw a post the other day talking about cats, Now, I love cats, They're great, But here's the thing: dogs are just the best, okay? There's no question about it, That is all,\",'2020-03-19',4),(4,'I am the night,','To all you lowly criminals out there, this is a warning to know I am watching, I am justice, I am righteousness, I am the NIGHT,','2020-03-24',1),(5,'Waka waka','waka waka waka waka waka waka waka waka waka waka waka waka waka waka waka waka','2020-03-31',9),(6,'Who is this Bob guy?',\"Decided to start tracking down this mysterious human known as 'Bob,' Who is Bob? What does he do? WHY does he do it? There is a lot of mystery surrounding this person, and I will be going into detail in future posts, Stay tuned!\",'2020-04-02',8),(7,'Re: I love cats,',\"A reader recently reached out to me about my last post, To be clear, I'm not dissing our canine companions! But we've got to be honest here, why are cats better? They're smart, affectionate, and great cuddle partners, Cats are better, It's just fact,\",'2020-04-04',3),(8,'Scooby Dooby Doo!',\"The search for scooby snacks: Where did they go? I know this whole quarantine thing is affecting businesses, but aren't scooby snacks counted as an essential service? Please post below if you find anything! I'm going crazy here!\",'2020-04-05',10),(9,'Bob Update','Dear readers, I know you have been waiting anxiously for an update on Bob, but there is not much to share so far, He appears to have little to no online presence, Just a clarification: I am decidedly NOT Bob, Thanks all, Stay tuned for more!','2020-04-06',8),(10,'Lizard People,',\"What are your guys' thoughts on them? I, for one, welcome out reptitlian overlords,\",'2020-04-12',5)",
    "UNLOCK TABLES",
    "CREATE TABLE blogstags (`blogid` int unsigned NOT NULL,`tag` varchar(20) CHARACTER SET utf8mb4 NOT NULL,PRIMARY KEY (`blogid`,`tag`),CONSTRAINT `blogstags_ibfk_1` FOREIGN KEY (`blogid`) REFERENCES blogs (`blogid`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci",
    "LOCK TABLES `blogstags` WRITE",
    "INSERT INTO blogstags VALUES (1,'hello world'),(2,'animals'),(2,'cats'),(3,'animals'),(3,'dogs'),(4,'crime'),(4,'justice'),(5,'cartoon'),(5,'waka'),(6,'bob'),(6,'update'),(7,'cats'),(7,'dogs'),(8,'dogs'),(8,'quarantine'),(8,'scooby snacks'),(9,'bob'),(9,'update'),(10,'lizards')",
    "UNLOCK TABLES",
    "CREATE TABLE comments (`commentid` int NOT NULL AUTO_INCREMENT,`sentiment` varchar(20) CHARACTER SET utf8mb4 DEFAULT NULL,`description` varchar(250) CHARACTER SET utf8mb4 DEFAULT NULL,`cdate` date DEFAULT NULL,`blogid` int unsigned DEFAULT NULL,`authorid` int DEFAULT NULL,PRIMARY KEY (`commentid`),CONSTRAINT `comments_ibfk_1` FOREIGN KEY (`blogid`) REFERENCES blogs (`blogid`),CONSTRAINT `comments_ibfk_2` FOREIGN KEY (`authorid`) REFERENCES users (`userid`),CONSTRAINT `sentiment_types` CHECK ((`sentiment` in (_utf8mb4'negative',_utf8mb4'positive')))) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci",
    "CREATE INDEX `comments_ibfk_2` ON comments (`blogid`)",
    "CREATE INDEX `test_idx` ON comments (`authorid`)",
    "LOCK TABLES `comments` WRITE",
    "INSERT INTO comments VALUES (1,'negative',\"Cats are cool and all, but dogs are where it's at,\",'2020-03-17',2,4),(2,'negative',\"What's all the hype about? Cats are clearly superior,\",'2020-03-20',3,3),(3,'positive','Nice,','2020-03-20',4,10),(4,'positive',\"Who IS Bob? I can't wait to find out,\",'2020-04-02',6,6),(5,'negative',\"I guess cat people just don't know what they're missing,\",'2020-04-05',7,4),(6,'positive','This is totally unrelated, but I just wanted to say I am a HUGE fan of yours, I love your work!','2020-04-05',8,4),(7,'positive',\"Have you checked out Dog-Mart? They've got everything,\",'2020-04-06',8,7),(8,'negative',\"I was hoping there'd be more of an update, Sorry, Bob,\",'2020-04-07',9,6),(9,'positive',\"I think they're all secretly cats, Open your eyes, sheeple!\",'2020-04-13',10,4),(10,'negative','Who? Me? Multimillionaire philanthropist of Arkham? A lizard person? Nope, Nothing to see here!','2020-04-15',10,1)",
    "UNLOCK TABLES",
    "CREATE TABLE follows (`leaderid` int NOT NULL,`followerid` int NOT NULL,PRIMARY KEY (`leaderid`,`followerid`),CONSTRAINT `follows_ibfk_1` FOREIGN KEY (`leaderid`) REFERENCES users (`userid`),CONSTRAINT `follows_ibfk_2` FOREIGN KEY (`followerid`) REFERENCES users (`userid`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci",
    "CREATE INDEX `follows_ibfk_2_idx` ON follows (`followerid`)",
    "LOCK TABLES `follows` WRITE",
    "INSERT INTO follows VALUES (6,2),(1,3),(4,3),(3,4),(6,5),(9,7),(2,8),(5,8),(1,9),(10,9),(4,10),(9,10)",
    "UNLOCK TABLES",
    "CREATE TABLE hobbies (`userid` int NOT NULL,`hobby` varchar(20) CHARACTER SET utf8mb4 NOT NULL,PRIMARY KEY (`hobby`,`userid`),CONSTRAINT `hobbies_ibfk_1` FOREIGN KEY (`userid`) REFERENCES users (`userid`),CONSTRAINT `hobby_types` CHECK ((`hobby` in (_utf8mb4'hiking',_utf8mb4'swimming',_utf8mb4'calligraphy',_utf8mb4'bowling',_utf8mb4'movie',_utf8mb4'cooking',_utf8mb4'dancing')))) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci",
    "CREATE INDEX `test_idx` ON hobbies (`userid`)",
    "LOCK TABLES `hobbies` WRITE",
    "INSERT INTO hobbies VALUES (1,'movie'),(2,'movie'),(3,'movie'),(4,'hiking'),(5,'dancing'),(5,'movie'),(6,'hiking'),(7,'bowling'),(8,'calligraphy'),(9,'dancing'),(9,'movie'),(10,'cooking')",
    "UNLOCK TABLES"
    ]
?>